### ISSUE TITLE
Variable people_per_heading

### ISSUE THREAD

**Issue by tnguyenh** [agrignard/URBAM#1]
Est-ce que la variable people_per_heading dans la species road est censée servir à quelque chose à un moment ? Où on peut l'enlever ?

**Comment by ptaillandier** [comment]
oui, tu peux la supprimer. c'était un test,  j'ai du la commiter par erreir.

Le ven. 28 sept. 2018 à 17:15, Tri Nguyen-Huu <notifications@github.com> a
écrit :

**Comment by tnguyenh** [comment]
ok merci
