### ISSUE TITLE
Create cell with id=0

### ISSUE THREAD

**Issue by agrignard** [agrignard/URBAM#5]
When loading grid from file, as soon as there is a building  initialized there is no way to remove it (it we put id =0 in the next file the current building won't be erase)

I don't know if I introduced something lately or if it was like that from the beginning.

**Comment by ptaillandier** [comment]
I don't remember, but it should be easy to just specify that if we get
'value = 0', then GAMA have to remove the building (there is an action
called something like "remove" that allows removing a building in a clean
way).

Le mar. 2 oct. 2018 à 16:28, Arnaud Grignard <notifications@github.com> a
écrit :

**Comment by agrignard** [comment]
yep done
